[profile.default]
src = 'contracts'
out = 'out'
solc_version = '0.8.19'
optimizer_runs = 1000000
via_ir = false
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'foundry-cache'
gas_reports = ["GovernorPortal", "CrossChainGovernorPortal"]
bytecode_hash = "none"
ffi = false

[fuzz]
runs = 256 #50000000

[invariant]
runs = 16  #1024
depth = 64  #4096