[profile.default]
src = 'contracts'
out = 'out'
solc_version = '0.8.19'
optimizer_runs = 1000000
via_ir = false
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'foundry-cache'
gas_reports = ["BaseChainPortal", "CrossChainPortal", "CrossChainGovernorExecutor"]
bytecode_hash = "none"
ffi = false

[fuzz]
runs = 512

[invariant]
runs = 32
depth = 128